apiVersion: v1
kind: Namespace
metadata:
  name: ior
  labels:
    istio-injection: disabled

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ior
  namespace: ior

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: ior
rules:
- apiGroups: ["route.openshift.io"]
  resources: ["routes", "routes/custom-host"]
  verbs: ["get", "list", "watch", "create", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: ior
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ior
subjects:
  - kind: ServiceAccount
    name: ior
    namespace: ior

---
apiVersion: v1
kind: Pod
metadata:
  name: ior
  namespace: ior
spec:
  serviceAccountName: ior
  containers:
  - name: ior
    image: ior
    imagePullPolicy: IfNotPresent
