apiVersion: v1
kind: Namespace
metadata:
  name: ${NAMESPACE}
  labels:
    istio-injection: disabled

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ior
  namespace: ${NAMESPACE}

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: ior
  namespace: ${NAMESPACE}
rules:
- apiGroups: ["route.openshift.io"]
  resources: ["routes", "routes/custom-host"]
  verbs: ["get", "list", "watch", "create", "delete"]
- apiGroups: [""]
  resources: ["services", "pods"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: ior
  namespace: ${NAMESPACE}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ior
subjects:
  - kind: ServiceAccount
    name: ior
    namespace: ${NAMESPACE}

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ior
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        maistra: ior
    spec:
      serviceAccountName: ior
      containers:
      - image: ${HUB}/ior:${TAG}
        imagePullPolicy: Always
        name: ior
        args:
          - --log_output_level=default:debug
